version: "3.2"

services:
  db_vet:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db_vet
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - ${DB_PORT}:1433
    restart: always
